### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pretech86** [hXR16F/Extension-Spoofer#1]
thanks for the nice programe but i have the following error 

# Extension spoofer by hXR16F
Params = ['saint', 'exe', 'a', 'jpg', '']
        1 file(s) copied.
Error loading Python DLL 'D:\shared_folder_for_virtual_machines\Extension-Spoofer\release\python34.dll'.
LoadLibrary: The specified module could not be found.

please can you help

**Comment by hXR16F** [comment]
I think it's a problem of pyinstaller. I probably fixed it now, tell me if this error is still occuring.

**Comment by pretech86** [comment]
it working my dear thanks a lot
